#!/bin/bash

test_suite=$(mktemp) || exit 1

printf "Compiling jamerror...\n"
(cd .. && ./build) || exit 2

printf "Compiling test suite...\n"
g++ \
-Wfatal-errors -Werror \
-Wall -Wextra -Wpedantic \
-Wfloat-equal -Wsign-conversion -Wfloat-conversion \
-Wno-error=unused-but-set-parameter \
-Wno-error=unused-but-set-variable \
-Wno-error=unused-function \
-Wno-error=unused-label \
-Wno-error=unused-local-typedefs \
-Wno-error=unused-parameter \
-Wno-error=unused-result \
-Wno-error=unused-variable \
-Wno-error=unused-value \
-I ../include \
test.cpp \
../bin/libjamerror.a \
-o $test_suite \
|| exit 3

printf "Running test suite...\n"
$test_suite || exit 4
